### ISSUE TITLE
RFE: set the secondary scheduler verbosiness level

### ISSUE THREAD

**Issue by fromanirh** [openshift/secondary-scheduler-operator#13]
To troubleshoot the behaviour of a secondary scheduler, among the first thing we try is usually to increase the verbosiness level. Unless I'm mistaken, the only option atm is to edit the deployment asset and rebuild the operator, which is not very practical. It would be nice and convenient to have a flag in the API to drive the verbosiness level of the scheduler, defaulting to the current value.

**Comment by damemi** [comment]
+1, verbosity should be handled with the operator's `logLevel` fields, exactly how it is in the core scheduler operator: https://github.com/openshift/cluster-kube-scheduler-operator/blob/f442172/pkg/operator/targetconfigcontroller/targetconfigcontroller.go#L230-L243

**Comment by damemi** [comment]
Actually @fromanirh the operator does already have the code for this (see [here](https://github.com/openshift/secondary-scheduler-operator/blob/master/pkg/operator/target_config_reconciler.go#L205-L216)). Have you tried it yet? We should document it for sure

**Comment by fromanirh** [comment]
> Actually @fromanirh the operator does already have the code for this (see [here](https://github.com/openshift/secondary-scheduler-operator/blob/master/pkg/operator/target_config_reconciler.go#L205-L216)). Have you tried it yet? We should document it for sure

Ah, didn't notice! Will surely try it out ASAP and let you know.

**Comment by fromanirh** [comment]
> Actually @fromanirh the operator does already have the code for this (see [here](https://github.com/openshift/secondary-scheduler-operator/blob/master/pkg/operator/target_config_reconciler.go#L205-L216)). Have you tried it yet? We should document it for sure

I'm happy to report that it works well as you described.

With this CR
```yaml
apiVersion: operator.openshift.io/v1
kind: SecondaryScheduler
metadata:
  name: secondary-scheduler
  namespace: openshift-secondary-scheduler-operator
spec:
  managementState: Managed
  logLevel: Trace
  schedulerConfig: topo-aware-scheduler-config
  imageSpec: quay.io/fromani/k8s-sched-plugins:v0.0.2021111101
```

Got the expected result (snipped for brevity):
```yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-11-12T16:21:51Z"
  generateName: secondary-scheduler-7d6d44cb6c-
  labels:
    app: secondary-scheduler
    pod-template-hash: 7d6d44cb6c
  name: secondary-scheduler-7d6d44cb6c-zj8s4
  namespace: openshift-secondary-scheduler-operator
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: secondary-scheduler-7d6d44cb6c
    uid: 4ef78925-664e-46cd-b20a-e0e80afdce70
  resourceVersion: "940"
  uid: d469d5be-8ff5-458e-b921-3c9e4a3bf6e8
spec:
  containers:
  - args:
    - /bin/kube-scheduler
    - --config=/etc/kubernetes/config.yaml
    - -v=6
    image: quay.io/fromani/k8s-sched-plugins:v0.0.2021111101
    imagePullPolicy: IfNotPresent
    name: secondary-scheduler
    resources:
      limits:
        cpu: 100m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 500Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File

```

Posted this tiny improvement: https://github.com/openshift/secondary-scheduler-operator/pull/16
