### ISSUE TITLE
RFE: set the secondary scheduler image in the CR

### ISSUE THREAD

**Issue by fromanirh** [openshift/secondary-scheduler-operator#14]
Looking at the [API definition](https://github.com/openshift/secondary-scheduler-operator/blob/master/pkg/apis/secondaryscheduler/v1/types.go) it seems there is no way to set the secondary scheduler image. It seems that the only way to tell the operator which image to deploy is to [on the deployment manifest](https://github.com/openshift/secondary-scheduler-operator/blob/master/deploy/05_deployment.yaml)

If this is correct, it would be very much convenient to add a flag in the API to set the image pullspec. We can keep overriding that value with environment variables if needed.

**Comment by damemi** [comment]
Yeah, this is needed and we have an issue open for it already in https://github.com/openshift/secondary-scheduler-operator/issues/8, so closing this as a duplicate
/close

**Comment by fromanirh** [comment]
Ah sorry @damemi missed that! I'll watching #8 . Thanks!
