### ISSUE TITLE
with latest built operator images,  error logs reported every 10min

### ISSUE THREAD

**Issue by libzhang** [openshift/secondary-scheduler-operator#72]
Setup:
openshift 4.11

Error logs, 
```
I1209 02:36:06.851773       1 shared_informer.go:247] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::client-ca-file
I1209 02:36:06.858126       1 base_controller.go:72] Caches are synced for LoggingSyncer
I1209 02:36:06.858143       1 base_controller.go:109] Starting #1 worker of LoggingSyncer controller ...
E1209 02:46:06.773198       1 target_config_reconciler.go:338] {configmap my-custom-scheduler-config} failed with : could not get configuration configmap: configmap "secondary-scheduler-config" not found
E1209 02:46:06.781812       1 target_config_reconciler.go:338] {configmap my-custom-scheduler-config} failed with : could not get configuration configmap: configmap "secondary-scheduler-config" not found
E1209 02:46:06.794765       1 target_config_reconciler.go:338] {configmap my-custom-scheduler-config} failed with : could not get configuration configmap: configmap "secondary-scheduler-config" not found
E1209 02:46:06.963972       1 target_config_reconciler.go:338] {configmap my-custom-scheduler-config} failed with : could not get configuration configmap: configmap "secondary-scheduler-config" not found
E1209 02:46:07.163888       1 target_config_reconciler.go:338] {configmap my-custom-scheduler-config} failed with : could not get configuration configmap: configmap "secondary-scheduler-config" not found
E1209 02:46:07.562933       1 target_config_reconciler.go:338] {configmap my-custom-scheduler-config} failed with : could not get configuration configmap: configmap "secondary-scheduler-config" not found
E1209 02:46:07.763993       1 target_config_reconciler.go:338] {configmap my-custom-scheduler-config} failed with : could not get configuration configmap: configmap "secondary-scheduler-config" not found

```

These logs reported even the configmap  _secondary-scheduler-config_ is there. Although we don't use that config. we use _my-custom-scheduler-config_.

Some investigation:
1. this change is added by #71,  it is using a hard code "secondary-scheduler-config". 
2.  As I described above,  even secondary-scheduler-config is existed,  it is still reporting this error, that means below api is not working correctly,  https://github.com/openshift/secondary-scheduler-operator/blob/c6fe67f922d6ffacfb65ec9952e2df3717ae5379/pkg/operator/target_config_reconciler.go#L186,

I built a test image to replace it with below api,  it is working as expected. 
https://github.com/openshift/secondary-scheduler-operator/blob/c6fe67f922d6ffacfb65ec9952e2df3717ae5379/pkg/operator/target_config_reconciler.go#L172

Need Help,
1. What's the expected behavior ?  is my above test image the correct behavior ? 
2. should we also remove this line https://github.com/openshift/secondary-scheduler-operator/blob/c6fe67f922d6ffacfb65ec9952e2df3717ae5379/pkg/operator/target_config_reconciler.go#L133,
as it is mis-understanding,  with new code,   the force redeployment may not happen.

**Comment by ingvagabund** [comment]
@libzhang this is a valid bug. Thank you for reporting

**Comment by libzhang** [comment]
Hi @ingvagabund,  thanks for taking this issue.  and I still have some questions need your help to understand, 
1. what's the difference b/w below 2 apis(sharedInformerFactory and kubeClient) ?  from my testing,  it looks the first one could not work properly as I described above, 
```
required, err := c.sharedInformerFactory.Core().V1().ConfigMaps().Lister().ConfigMaps(secondaryScheduler.Namespace).Get() 
```
and 
```
 required, err = c.kubeClient.CoreV1().ConfigMaps(secondaryScheduler.Namespace).Get()
```
2. why every 10 minutes, the sync will happened ? even the configmap is not changed?  where does this timer(10minutes) come from ?
3.  should we also remove this line https://github.com/openshift/secondary-scheduler-operator/blob/c6fe67f922d6ffacfb65ec9952e2df3717ae5379/pkg/operator/target_config_reconciler.go#L133,
as it is mis-understanding, with new code, the force redeployment may not happen.

**Comment by ingvagabund** [comment]
The `sharedInformerFactory` allows to read the config map from a local cache (which is continuously updated after a new cm is created/updated/deleted) to avoid directly accessing the kube-apiserver through the `kubeClient` and thus reducing the traffic.
