### ISSUE TITLE
Allow users to define image url in secondaryscheduler spec field.

### ISSUE THREAD

**Issue by wangchen615** [openshift/secondary-scheduler-operator#8]
We need to introduce a field `image` in SecondaryScheduler CRD to allow users to define their own image URL in secondaryscheduler CR yaml.

**Comment by damemi** [comment]
+1 this is an important usability feature

**Comment by damemi** [comment]
Opened https://github.com/openshift/secondary-scheduler-operator/pull/15 to add this
