### ISSUE TITLE
Master branch build failed as go version is 1.18, need to update dockerfile to use  go version 1.19 

### ISSUE THREAD

**Issue by yanxiucai** [openshift/secondary-scheduler-operator#89]
Current mater branch build failed, error message as below:

Step 1/8 : FROM registry.ci.openshift.org/openshift/release:golang-1.18 AS builder
 ---> cd5ce8805a12
Step 2/8 : WORKDIR /go/src/github.com/openshift/secondary-scheduler-operator
 ---> Using cache
 ---> aa5545d61a7a
Step 3/8 : COPY . .
 ---> Using cache
 ---> a582b2144c8e
Step 4/8 : RUN make build
 ---> Running in 50131e86c7fb
fatal: No names found, cannot describe anything.
go build -trimpath -ldflags "-X github.com/openshift/secondary-scheduler-operator/pkg/version.versionFromGit="v0.0.0-unknown-8a26909" -X github.com/openshi  ft/secondary-scheduler-operator/pkg/version.commitFromGit="8a26909" -X github.com/openshift/secondary-scheduler-operator/pkg/version.gitTreeState="clean" -  X github.com/openshift/secondary-scheduler-operator/pkg/version.buildDate="2023-05-22T03:12:15Z" " github.com/openshift/secondary-scheduler-operator/cmd/se  condary-scheduler-operator
# k8s.io/component-base/metrics
vendor/k8s.io/component-base/metrics/registry.go:35:29: undefined: atomic.Bool
note: module requires Go 1.19
make: *** [build] Error 2
The command '/bin/sh -c make build' returned a non-zero code: 2

After update https://github.com/openshift/secondary-scheduler-operator/blob/master/Dockerfile#L1 to go 1.19, build passed.

**Comment by yanxiucai** [comment]
Cool! Thanks for the quick feedback!

**Comment by ingvagabund** [comment]
https://github.com/openshift/secondary-scheduler-operator/pull/88 merged
/close
