### ISSUE TITLE
base image need to be upgraded because RHEL 7.6 was end of maintenance.

### ISSUE THREAD

**Issue by yimingwangdell** [openshift/secondary-scheduler-operator#92]
We security team find around 500 CVEs in secondary-scheduler-operator image:
https://github.com/openshift/secondary-scheduler-operator/blob/master/Dockerfile

which use RHEL 7.6 as base image, we need to upgrade it to 8.x or 9.x to get rid of security issues.

Thanks!

**Comment by ingvagabund** [comment]
@yimingwangdell the mentioned [Dockerfile](https://github.com/openshift/secondary-scheduler-operator/blob/master/Dockerfile) is not used for building the actual image. It is used only for developer purposes.
/close
